# parent or base image
FROM node:17-alpine

#working directory in the container 
WORKDIR /app 

#copying the package.json source codes file to the working directory
COPY . .

RUN npm install/app

EXPOSE 4000

CMD ["node", "app.js"]